// <auto-generated />
using AfetToplanmaAlani.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AfetToplanmaAlani.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("AfetToplanmaAlani.EL.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlaceCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlaceCategoryId");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "İstanbul",
                            ContactNumber = "02120000000",
                            District = "Kadıköy",
                            Latitude = 40.988999999999997,
                            Longitude = 29.027999999999999,
                            Name = "Merkez Park Toplanma Alanı",
                            Neighborhood = "Fenerbahçe",
                            PlaceCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            City = "İstanbul",
                            ContactNumber = "02120000001",
                            District = "Kadıköy",
                            Latitude = 40.991199999999999,
                            Longitude = 29.0321,
                            Name = "Moda Çadır Alanı",
                            Neighborhood = "Moda",
                            PlaceCategoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            City = "İstanbul",
                            ContactNumber = "02120000002",
                            District = "Avcılar",
                            Latitude = 40.979100000000003,
                            Longitude = 28.722100000000001,
                            Name = "Avcılar Su Tesisi",
                            Neighborhood = "Cihangir",
                            PlaceCategoryId = 3
                        },
                        new
                        {
                            Id = 4,
                            City = "İstanbul",
                            ContactNumber = "02120000003",
                            District = "Bakırköy",
                            Latitude = 40.980499999999999,
                            Longitude = 28.874199999999998,
                            Name = "Bakırköy Fırını",
                            Neighborhood = "Kartaltepe",
                            PlaceCategoryId = 4
                        },
                        new
                        {
                            Id = 5,
                            City = "İstanbul",
                            ContactNumber = "02120000004",
                            District = "Beşiktaş",
                            Latitude = 41.043799999999997,
                            Longitude = 29.009399999999999,
                            Name = "Beşiktaş Eczanesi",
                            Neighborhood = "Levent",
                            PlaceCategoryId = 5
                        },
                        new
                        {
                            Id = 6,
                            City = "Ankara",
                            ContactNumber = "03120000000",
                            District = "Çankaya",
                            Latitude = 39.9208,
                            Longitude = 32.854100000000003,
                            Name = "Kızılay Toplanma Alanı",
                            Neighborhood = "Kızılay",
                            PlaceCategoryId = 1
                        },
                        new
                        {
                            Id = 7,
                            City = "Ankara",
                            ContactNumber = "03120000001",
                            District = "Çankaya",
                            Latitude = 39.933399999999999,
                            Longitude = 32.859699999999997,
                            Name = "Bahçelievler Çadır Alanı",
                            Neighborhood = "Bahçelievler",
                            PlaceCategoryId = 2
                        },
                        new
                        {
                            Id = 8,
                            City = "Ankara",
                            ContactNumber = "03120000002",
                            District = "Altındağ",
                            Latitude = 39.927199999999999,
                            Longitude = 32.863999999999997,
                            Name = "Ulus Su Tesisi",
                            Neighborhood = "Ulus",
                            PlaceCategoryId = 3
                        },
                        new
                        {
                            Id = 9,
                            City = "Ankara",
                            ContactNumber = "03120000003",
                            District = "Mamak",
                            Latitude = 39.945999999999998,
                            Longitude = 32.857999999999997,
                            Name = "Mamak Fırını",
                            Neighborhood = "OSB",
                            PlaceCategoryId = 4
                        },
                        new
                        {
                            Id = 10,
                            City = "Ankara",
                            ContactNumber = "03120000004",
                            District = "Yenimahalle",
                            Latitude = 39.9512,
                            Longitude = 32.753399999999999,
                            Name = "Yenimahalle Eczanesi",
                            Neighborhood = "Batıkent",
                            PlaceCategoryId = 5
                        },
                        new
                        {
                            Id = 11,
                            City = "İzmir",
                            ContactNumber = "02320000000",
                            District = "Konak",
                            Latitude = 38.419199999999996,
                            Longitude = 27.128699999999998,
                            Name = "Alsancak Toplanma Alanı",
                            Neighborhood = "Alsancak",
                            PlaceCategoryId = 1
                        },
                        new
                        {
                            Id = 12,
                            City = "İzmir",
                            ContactNumber = "02320000001",
                            District = "Konak",
                            Latitude = 38.414900000000003,
                            Longitude = 27.1282,
                            Name = "Göztepe Çadır Alanı",
                            Neighborhood = "Göztepe",
                            PlaceCategoryId = 2
                        },
                        new
                        {
                            Id = 13,
                            City = "İzmir",
                            ContactNumber = "02320000002",
                            District = "Bornova",
                            Latitude = 38.466000000000001,
                            Longitude = 27.221299999999999,
                            Name = "Bornova Su Tesisi",
                            Neighborhood = "Kazım Dirik",
                            PlaceCategoryId = 3
                        },
                        new
                        {
                            Id = 14,
                            City = "İzmir",
                            ContactNumber = "02320000003",
                            District = "Buca",
                            Latitude = 38.408499999999997,
                            Longitude = 27.111499999999999,
                            Name = "Buca Fırını",
                            Neighborhood = "Evka 3",
                            PlaceCategoryId = 4
                        },
                        new
                        {
                            Id = 15,
                            City = "İzmir",
                            ContactNumber = "02320000004",
                            District = "Karşıyaka",
                            Latitude = 38.451999999999998,
                            Longitude = 27.051100000000002,
                            Name = "Karşıyaka Eczanesi",
                            Neighborhood = "Alaybey",
                            PlaceCategoryId = 5
                        },
                        new
                        {
                            Id = 16,
                            City = "Bursa",
                            ContactNumber = "02240000000",
                            District = "Osmangazi",
                            Latitude = 40.189700000000002,
                            Longitude = 29.061699999999998,
                            Name = "Nilüfer Toplanma Alanı",
                            Neighborhood = "Nilüfer",
                            PlaceCategoryId = 1
                        },
                        new
                        {
                            Id = 17,
                            City = "Bursa",
                            ContactNumber = "02240000001",
                            District = "Osmangazi",
                            Latitude = 40.200200000000002,
                            Longitude = 29.072299999999998,
                            Name = "Beşevler Çadır Alanı",
                            Neighborhood = "Beşevler",
                            PlaceCategoryId = 2
                        },
                        new
                        {
                            Id = 18,
                            City = "Bursa",
                            ContactNumber = "02240000002",
                            District = "Yıldırım",
                            Latitude = 40.197000000000003,
                            Longitude = 29.074999999999999,
                            Name = "Hüdavendigar Su Tesisi",
                            Neighborhood = "Hüdavendigar",
                            PlaceCategoryId = 3
                        },
                        new
                        {
                            Id = 19,
                            City = "Bursa",
                            ContactNumber = "02240000003",
                            District = "Nilüfer",
                            Latitude = 40.185000000000002,
                            Longitude = 28.989999999999998,
                            Name = "Görükle Fırını",
                            Neighborhood = "Görükle",
                            PlaceCategoryId = 4
                        },
                        new
                        {
                            Id = 20,
                            City = "Bursa",
                            ContactNumber = "02240000004",
                            District = "Osmangazi",
                            Latitude = 40.203000000000003,
                            Longitude = 29.055,
                            Name = "Altınova Eczanesi",
                            Neighborhood = "Altınova",
                            PlaceCategoryId = 5
                        },
                        new
                        {
                            Id = 21,
                            City = "Ankara",
                            ContactNumber = "03120000005",
                            District = "Çankaya",
                            Latitude = 39.933100000000003,
                            Longitude = 32.859000000000002,
                            Name = "Sıhhiye Toplanma Alanı",
                            Neighborhood = "Sıhhiye",
                            PlaceCategoryId = 1
                        },
                        new
                        {
                            Id = 22,
                            City = "Ankara",
                            ContactNumber = "03120000006",
                            District = "Çankaya",
                            Latitude = 39.933999999999997,
                            Longitude = 32.859999999999999,
                            Name = "Bahçelievler Çadır Alanı",
                            Neighborhood = "Bahçelievler",
                            PlaceCategoryId = 2
                        },
                        new
                        {
                            Id = 23,
                            City = "Ankara",
                            ContactNumber = "03120000007",
                            District = "Çankaya",
                            Latitude = 39.932000000000002,
                            Longitude = 32.854999999999997,
                            Name = "Kızılay Su Tesisi",
                            Neighborhood = "Kızılay",
                            PlaceCategoryId = 3
                        },
                        new
                        {
                            Id = 24,
                            City = "Ankara",
                            ContactNumber = "03120000008",
                            District = "Çankaya",
                            Latitude = 39.935000000000002,
                            Longitude = 32.857999999999997,
                            Name = "Çankaya Fırını",
                            Neighborhood = "Çankaya",
                            PlaceCategoryId = 4
                        },
                        new
                        {
                            Id = 25,
                            City = "Ankara",
                            ContactNumber = "03120000009",
                            District = "Yenimahalle",
                            Latitude = 39.951000000000001,
                            Longitude = 32.753,
                            Name = "Batıkent Eczanesi",
                            Neighborhood = "Batıkent",
                            PlaceCategoryId = 5
                        },
                        new
                        {
                            Id = 26,
                            City = "İzmir",
                            ContactNumber = "02320000005",
                            District = "Karşıyaka",
                            Latitude = 38.451000000000001,
                            Longitude = 27.052,
                            Name = "Karşıyaka Toplanma Alanı",
                            Neighborhood = "Karşıyaka",
                            PlaceCategoryId = 1
                        },
                        new
                        {
                            Id = 27,
                            City = "İzmir",
                            ContactNumber = "02320000006",
                            District = "Karşıyaka",
                            Latitude = 38.454999999999998,
                            Longitude = 27.050000000000001,
                            Name = "Bostanlı Çadır Alanı",
                            Neighborhood = "Bostanlı",
                            PlaceCategoryId = 2
                        },
                        new
                        {
                            Id = 28,
                            City = "İzmir",
                            ContactNumber = "02320000007",
                            District = "Bornova",
                            Latitude = 33.466000000000001,
                            Longitude = 27.221,
                            Name = "Bornova Su Tesisi2",
                            Neighborhood = "Kazım Dirik",
                            PlaceCategoryId = 3
                        },
                        new
                        {
                            Id = 29,
                            City = "İzmir",
                            ContactNumber = "02320000008",
                            District = "Konak",
                            Latitude = 38.417000000000002,
                            Longitude = 27.128,
                            Name = "Konak Fırını",
                            Neighborhood = "Konak",
                            PlaceCategoryId = 4
                        },
                        new
                        {
                            Id = 30,
                            City = "İzmir",
                            ContactNumber = "02320000009",
                            District = "Konak",
                            Latitude = 38.414999999999999,
                            Longitude = 27.129000000000001,
                            Name = "Göztepe Eczanesi",
                            Neighborhood = "Göztepe",
                            PlaceCategoryId = 5
                        });
                });

            modelBuilder.Entity("AfetToplanmaAlani.EL.Models.PlaceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlaceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Toplanma Noktaları"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Çadır Alanları"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Su Tesisleri"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fırın"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Eczane"
                        });
                });

            modelBuilder.Entity("AfetToplanmaAlani.EL.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ali",
                            PhoneNumber = "5551112233",
                            PlaceId = 1,
                            Surname = "Yılmaz"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ayşe",
                            PhoneNumber = "5552223344",
                            PlaceId = 1,
                            Surname = "Demir"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mehmet",
                            PhoneNumber = "5553334455",
                            PlaceId = 5,
                            Surname = "Kaya"
                        });
                });

            modelBuilder.Entity("AfetToplanmaAlani.EL.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("AfetToplanmaAlani.EL.Models.VehicleStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleStaff");
                });

            modelBuilder.Entity("AfetToplanmaAlani.EL.Models.WorkGroupStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Crew")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Duty")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkGroupStaff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Crew = "AFAD",
                            Duty = "Lider",
                            Name = "Ali",
                            PhoneNumber = "5551110001",
                            Surname = "Yılmaz",
                            WorkGroup = "Bilgi Yönetimi Değerlendirme Ve Haberleşme Çalışma Grubu"
                        },
                        new
                        {
                            Id = 2,
                            Crew = "Kızılay",
                            Duty = "Üye",
                            Name = "Ayşe",
                            PhoneNumber = "5551110002",
                            Surname = "Demir",
                            WorkGroup = "Arama Kurtarma Çalışma Grubu"
                        },
                        new
                        {
                            Id = 3,
                            Crew = "AFAD",
                            Duty = "Üye",
                            Name = "Mehmet",
                            PhoneNumber = "5551110003",
                            Surname = "Kaya",
                            WorkGroup = "Barınma Çalışma Grubu"
                        },
                        new
                        {
                            Id = 4,
                            Crew = "Kızılay",
                            Duty = "Üye",
                            Name = "Fatma",
                            PhoneNumber = "5551110004",
                            Surname = "Öztürk",
                            WorkGroup = "Hasar Tespit Çalışma Grubu"
                        },
                        new
                        {
                            Id = 5,
                            Crew = "AFAD",
                            Duty = "Üye",
                            Name = "Ahmet",
                            PhoneNumber = "5551110005",
                            Surname = "Çelik",
                            WorkGroup = "Enkaz Kaldırma Çalışma Grubu"
                        },
                        new
                        {
                            Id = 6,
                            Crew = "Kızılay",
                            Duty = "Üye",
                            Name = "Elif",
                            PhoneNumber = "5551110006",
                            Surname = "Ak",
                            WorkGroup = "Yangın Çalışma Grubu"
                        },
                        new
                        {
                            Id = 7,
                            Crew = "AFAD",
                            Duty = "Üye",
                            Name = "Can",
                            PhoneNumber = "5551110007",
                            Surname = "Yıldız",
                            WorkGroup = "Beslenme Çalışma Grubu"
                        },
                        new
                        {
                            Id = 8,
                            Crew = "Kızılay",
                            Duty = "Üye",
                            Name = "Selin",
                            PhoneNumber = "5551110008",
                            Surname = "Arslan",
                            WorkGroup = "Sağlık Çalışma Grubu"
                        },
                        new
                        {
                            Id = 9,
                            Crew = "AFAD",
                            Duty = "Üye",
                            Name = "Deniz",
                            PhoneNumber = "5551110009",
                            Surname = "Kurt",
                            WorkGroup = "Ayni Bağış Ve Depo Yönetimi Çalışma Grubu"
                        },
                        new
                        {
                            Id = 10,
                            Crew = "Kızılay",
                            Duty = "Üye",
                            Name = "Burak",
                            PhoneNumber = "5551110010",
                            Surname = "Demirtaş",
                            WorkGroup = "Psikososyal Çalışma Grubu"
                        },
                        new
                        {
                            Id = 11,
                            Crew = "AFAD",
                            Duty = "Üye",
                            Name = "Derya",
                            PhoneNumber = "5551110011",
                            Surname = "Polat",
                            WorkGroup = "Güvenlik Ve Trafik Çalışma Grubu"
                        },
                        new
                        {
                            Id = 12,
                            Crew = "Kızılay",
                            Duty = "Üye",
                            Name = "Ege",
                            PhoneNumber = "5551110012",
                            Surname = "Kara",
                            WorkGroup = "Tahliye Yerleştirme Çalışma Grubu"
                        },
                        new
                        {
                            Id = 13,
                            Crew = "AFAD",
                            Duty = "Üye",
                            Name = "Merve",
                            PhoneNumber = "5551110013",
                            Surname = "Yalçın",
                            WorkGroup = "Afet Zarar Tespit Çalışma Grubu"
                        },
                        new
                        {
                            Id = 14,
                            Crew = "Kızılay",
                            Duty = "Üye",
                            Name = "Ozan",
                            PhoneNumber = "5551110014",
                            Surname = "Güneş",
                            WorkGroup = "Afet Kimliklendirme Ve Defin Çalışma Grubu"
                        },
                        new
                        {
                            Id = 15,
                            Crew = "AFAD",
                            Duty = "Üye",
                            Name = "Seda",
                            PhoneNumber = "5551110015",
                            Surname = "Erdoğan",
                            WorkGroup = "Afet Finans Ve Kaynak Yönetimi Çalışma Grubu"
                        },
                        new
                        {
                            Id = 16,
                            Crew = "Kızılay",
                            Duty = "Üye",
                            Name = "Kaan",
                            PhoneNumber = "5551110016",
                            Surname = "Öz",
                            WorkGroup = "Afet Tarım Orman Gıda Su Ve Hayvancılık Çalışma Grubu"
                        },
                        new
                        {
                            Id = 17,
                            Crew = "AFAD",
                            Duty = "Üye",
                            Name = "Nazlı",
                            PhoneNumber = "5551110017",
                            Surname = "Uçar",
                            WorkGroup = "Afet Enerji Çalışma Grubu"
                        },
                        new
                        {
                            Id = 18,
                            Crew = "Kızılay",
                            Duty = "Üye",
                            Name = "Emre",
                            PhoneNumber = "5551110018",
                            Surname = "Şahin",
                            WorkGroup = "Afet Haberleşme Çalışma Grubu"
                        },
                        new
                        {
                            Id = 19,
                            Crew = "AFAD",
                            Duty = "Üye",
                            Name = "Büşra",
                            PhoneNumber = "5551110019",
                            Surname = "Aydın",
                            WorkGroup = "Afet Ulaşım Alt Yapı Çalışma Grubu"
                        },
                        new
                        {
                            Id = 20,
                            Crew = "Kızılay",
                            Duty = "Üye",
                            Name = "Serkan",
                            PhoneNumber = "5551110020",
                            Surname = "Topal",
                            WorkGroup = "Afet Nakliye Çalışma Grubu"
                        });
                });

            modelBuilder.Entity("AfetToplanmaAlani.EL.Models.Place", b =>
                {
                    b.HasOne("AfetToplanmaAlani.EL.Models.PlaceCategory", "PlaceCategory")
                        .WithMany("Places")
                        .HasForeignKey("PlaceCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PlaceCategory");
                });

            modelBuilder.Entity("AfetToplanmaAlani.EL.Models.Staff", b =>
                {
                    b.HasOne("AfetToplanmaAlani.EL.Models.Place", "Place")
                        .WithMany("Staff")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Place");
                });

            modelBuilder.Entity("AfetToplanmaAlani.EL.Models.VehicleStaff", b =>
                {
                    b.HasOne("AfetToplanmaAlani.EL.Models.Vehicle", "Vehicle")
                        .WithMany("VehicleStaff")
                        .HasForeignKey("VehicleId");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AfetToplanmaAlani.EL.Models.Place", b =>
                {
                    b.Navigation("Staff");
                });

            modelBuilder.Entity("AfetToplanmaAlani.EL.Models.PlaceCategory", b =>
                {
                    b.Navigation("Places");
                });

            modelBuilder.Entity("AfetToplanmaAlani.EL.Models.Vehicle", b =>
                {
                    b.Navigation("VehicleStaff");
                });
#pragma warning restore 612, 618
        }
    }
}
